config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "animals#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :sightings
    validates :name, :latin_name, :kingdom, presence: true
    validates :name, uniqueness: true
    validates :name, :latin_name, :kingdom, format: {:with => /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/, message: 'should contain only letters'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
    belongs_to :animal
    validates :date, :time, :latitude, :longitude, presence: true
    validates :date, :time, :latitude, :longitude, format: {:with => /\A[\[\],\p{Zs}\p{N}]+\z/, message: 'should contain only numbers'}
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    def index
        @animal = Animal.all
        puts @animal
    end
    
    def new
        @animal = Animal.new
    end
    
    def create
        @animal = Animal.new(animal_params)
        if @animal.valid?
            @animal.save
            flash.now[:alert]= "#{@animal.name} has been Saved!"
            redirect_to '/animals'
            
        else 
            @errors = @animal.errors.full_messages
            render 'new'
        end
    end
    
    
    def edit 
        @animal = Animal.find(params[:id])
    end
    
    
    def update
        @animal = Animal.find(params[:id])
        if @animal.update(animal_params)
            redirect_to '/animals'
        else
            @errors = @animal.errors.full_messages
            render 'new'
        end
    end
    
    def show
        @animal = Animal.find(params[:id])
    end
    
    def destroy
        @animal = Animal.destroy(params[:id])
        redirect_to '/animals'
    end 
    
    private
    
    def animal_params
        params.require(:animal).permit(:name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    def new
        animal = Animal.find(params[:animal_id])
        @sighting = animal.sightings.new
        
    end
    
    def create
        @sighting = Sighting.new(sighting_params)
        if @sighting.save
            redirect_to animal_path(@sighting.animal)
        else
            @errors = @sighting.errors.full_messages
            render 'new'
        end
    end
    
    
    def edit
        @sighting = Sighting.find(params[:id])
    end

    def update
        @sighting = Sighting.find(params[:id])
        if @sighting.update(sighting_params)
            redirect_to :animal
        else
            @errors = @sighting.errors.full_messages
            render :new
        end
    end
    
    
    def destroy
        
        
    end
    
    private
    
    def sighting_params
        params.require(:sighting).permit(:animal_id, :date, :time, :latitude, :longitude)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/edit.html.erb
<h1>Edit Page</h1>



<%= form_for @animal do |f| %>
    <%= f.label 'animal name' %>
    <%= f.text_field :name %></br>
    
    <%= f.label :latin_name %>
    <%= f.text_field :latin_name %></br>
    
    <%= f.label :kingdom %>
    <%= f.text_field :kingdom %></br>
    <%= f.submit %>
    
    <%if @errors%>
 <% @errors.each do|msg| %>
 <p><%=msg%></p>
<%end%>
<%end%>

<%end%>

app/views/animals/index.html.erb
<h1>Ranger Page</h1>

<%= link_to 'Submit New Animal', new_animal_path %>

<ul>
    <%if @animal%>
 <% @animal.each do |a| %>
 <li><%=link_to a.name, animal_path(a)%>------<%= link_to 'Edit', edit_animal_path(a) %> <%= link_to 'Delete', animal_path(a), method: :delete %></li>
<%end%>
    <%end%>
</ul>

 

app/views/animals/new.html.erb
<h3>Submit A New Animal</h3>

  <%= form_for @animal do |f| %>
  <h4>Animal Name (Alpha Characters Only)</h4>
     <%= f.text_field :name %></br>

     <h4>Latin Name (Alpha Characters Only)</h4>
     <%= f.text_field :latin_name %></br>

     <h4>Kingdom Type (Select One)</h4>
     <%= f.radio_button :kingdom, 'Animal', :checked =>true %>
     <%= label :kingdom, 'Animal' %>
     </br>
     <%= f.radio_button :kingdom, 'Plants' %>
     <%= label :kingdom, 'Plants' %>
     </br>
     <%= f.radio_button :kingdom, 'Protists' %>
     <%= label :kingdom, 'Protists' %>
     </br>
     <%= f.radio_button :kingdom, 'Fungi' %>
     <%= label :kingdom, 'Fungi' %>
     </br>
     <%= f.radio_button :kingdom, 'Archaebacteria' %>
     <%= label :kingdom, 'Archaebacteria' %>
     </br>
     <%= f.radio_button :kingdom, 'ubacteria' %>
     <%= label :kingdom, 'Ubacteria' %>
     </br>
     </br>
     <%= f.submit %>

     <%if @errors%>
        <% @errors.each do|msg| %>
        <p><%=msg%></p>
     <%end%>
  <%end%>
<%end%>

app/views/animals/show.html.erb
<h2><%= @animal.name %>
<%= @animal.latin_name %>
<%= @animal.kingdom %>
</h2>


<%=link_to "Report Sighting", new_sighting_path(animal_id: @animal.id) %>






<h3>Reported Sightings:</h3>
<ul>
 <% @animal.sightings.each do |sighting| %>
 <li>Date: <%=sighting.date%></br>
 Time: <%=sighting.latitude%></br>
 Latitude: <%=sighting.latitude%></br>
 Longitude: <%=sighting.longitude%></li>
 <%=link_to "Edit Sighting", edit_sighting_path(sighting) %>
 </br>
 </br>
<%end%>
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>EDIT PAGE</h1>
​
<%= form_for @sighting do |f| %>
​
 <%=f.hidden_field :animal_id%>
​
  <h4>Date</h4>
  <%= f.text_field :date %></br>
​
  <h4>Time</h4>
  <%= f.text_field :time %></br>
​
  <h4>Latitude</h4>
  <%= f.text_field :latitude %></br>
​
  <h4>Longitude</h4>
  <%= f.text_field :longitude %></br>
​
<%= f.submit %>
​
<%if @errors%>
 <%@errors.each do |errors| %>
  <p><%=errors%></p>
 <%end%>
<%end%>
​
<%end%>

app/views/sightings/new.html.erb
<h1>Enter your sighting</h1>

<%= form_for @sighting do |f| %>
    <%= f. hidden_field :animal_id %>
     <h4>Date:</h4>
     <%= f.text_field :date %></br>

     <h4>Time:</h4>
     <%= f.text_field :time %></br>
     </br>
     <h4>Latitude:</h4>
     <%= f.text_field :latitude %></br>
     </br>
     <h4>Longitude:</h4>
     <%= f.text_field :longitude %></br>
     </br>
     <%= f.submit %>

     <%if @errors%>
        <% @errors.each do|msg| %>
        <p><%=msg%></p>
     <%end%>
  <%end%>
<%end%>